# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {Common-41} -limit 4294967295
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/CPU/CPU.cache/wt [current_project]
set_property parent.project_path F:/CPU/CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  F:/CPU/CPU.srcs/sources_1/new/RelativeCompare.v
  F:/CPU/CPU.srcs/sources_1/new/read_reg.v
  F:/CPU/CPU.srcs/sources_1/new/rcomp.v
  F:/CPU/CPU.srcs/sources_1/new/Relative_Check2.v
  F:/CPU/CPU.srcs/sources_1/new/Rc2.v
  F:/CPU/CPU.srcs/sources_1/imports/sources_1/new/opctl.v
  F:/CPU/CPU.srcs/sources_1/imports/sources_1/new/ctl2.v
  F:/CPU/CPU.srcs/sources_1/imports/sources_1/new/ctl1.v
  F:/CPU/CPU.srcs/sources_1/imports/sources_1/new/ac.v
  F:/CPU/CPU.srcs/sources_1/imports/sources_1/imports/new/register_nbits.v
  F:/CPU/CPU.srcs/sources_1/imports/sources_1/imports/new/rom.v
  F:/CPU/CPU.srcs/sources_1/new/Relative_Check1.v
  F:/CPU/CPU.srcs/sources_1/imports/sources_1/imports/new/regfile.v
  F:/CPU/CPU.srcs/sources_1/new/Re2.v
  F:/CPU/CPU.srcs/sources_1/imports/sources_1/imports/new/ram.v
  F:/CPU/CPU.srcs/sources_1/imports/sources_1/new/NPC.v
  F:/CPU/CPU.srcs/sources_1/imports/sources_1/new/Mem_WB.v
  F:/CPU/CPU.srcs/sources_1/imports/sources_1/new/IR.v
  F:/CPU/CPU.srcs/sources_1/imports/sources_1/new/IF_ID.v
  F:/CPU/CPU.srcs/sources_1/imports/sources_1/new/ID_EX.v
  F:/CPU/CPU.srcs/sources_1/imports/sources_1/imports/classdesign/dclk.v
  F:/CPU/CPU.srcs/sources_1/imports/sources_1/new/Control.v
  F:/CPU/CPU.srcs/sources_1/imports/sources_1/new/ALUctl.v
  F:/CPU/CPU.srcs/sources_1/imports/sources_1/imports/new/alu.v
  F:/CPU/CPU.srcs/sources_1/imports/7_trans.v
  F:/CPU/CPU.srcs/sources_1/imports/sources_1/new/EX_Mem.v
  F:/CPU/CPU.srcs/sources_1/imports/sources_1/new/main.v
}
read_xdc F:/CPU/CPU.srcs/constrs_1/imports/new/trl.xdc
set_property used_in_implementation false [get_files F:/CPU/CPU.srcs/constrs_1/imports/new/trl.xdc]

synth_design -top main -part xc7a100tcsg324-1
write_checkpoint -noxdef main.dcp
catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
